const RestaurantsData = [
    {
      id: '1',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/v3tt-listing.jpg',
      title: 'Rose Garden Restaurant',
      subtitle: 'Burgers - Chicken - Rice - Wings',
      reviewStar: '4.7',
      deliveryCharges: 'Free',
      time: '20 min',
    },
    {
      id: '2',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/rji9-listing.jpg?width=400&height=225',
      title: 'Sunset Diner',
      subtitle: 'Pizza - Pasta - Salads',
      reviewStar: '4.5',
      deliveryCharges: 'Rs. 50',
      time: '25 min',
    },
    {
      id: '3',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/zet7-listing.jpg?width=400&height=225',
      title: 'Ocean Breeze Bistro',
      subtitle: 'Seafood - Sushi - Cocktails',
      reviewStar: '4.8',
      deliveryCharges: 'Rs. 70',
      time: '30 min',
    },
    {
      id: '4',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/n7tb-listing.jpg?width=400&height=225',
      title: 'Spicy Haven',
      subtitle: 'Indian - Spicy - Vegetarian',
      reviewStar: '4.6',
      deliveryCharges: 'Free',
      time: '15 min',
    },
    {
      id: '5',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/gv2y-listing.jpg?width=400&height=225',
      title: 'The Breakfast Club',
      subtitle: 'Pancakes - Waffles - Smoothies',
      reviewStar: '4.4',
      deliveryCharges: 'Rs. 20',
      time: '20 min',
    },
    {
      id: '6',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/n4pb-listing.jpg?width=400&height=225',
      title: 'Taco Town',
      subtitle: 'Tacos - Burritos - Nachos',
      reviewStar: '4.7',
      deliveryCharges: 'Rs. 30',
      time: '22 min',
    },
    {
      id: '7',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/j722-listing.jpg?width=400&height=225',
      title: 'Vegan Vibes',
      subtitle: 'Vegan - Organic - Healthy',
      reviewStar: '4.9',
      deliveryCharges: 'Free',
      time: '18 min',
    },
    {
      id: '8',
      img: 'https://images.deliveryhero.io/image/fd-pk/LH/s290-listing.jpg?width=400&height=225',
      title: 'Burger Haven',
      subtitle: 'Gourmet Burgers - Fries - Shakes',
      reviewStar: '4.6',
      deliveryCharges: 'Rs. 40',
      time: '28 min',
    },
  ];
  
  export default RestaurantsData;